# Generated by Django 4.1.4 on 2022-12-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mcuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'mcuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mcusermovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_played', models.BooleanField()),
                ('is_recommended', models.BooleanField()),
                ('is_liked', models.BooleanField()),
                ('is_saved', models.BooleanField()),
                ('play_runtime', models.FloatField()),
                ('play_date', models.DateField()),
            ],
            options={
                'db_table': 'mcusermovie',
                'managed': False,
            },
        ),
    ]
