# Generated by Django 4.1.4 on 2022-12-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='McUserMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_played', models.BooleanField()),
                ('is_recommended', models.BooleanField()),
                ('is_liked', models.BooleanField()),
                ('is_saved', models.BooleanField()),
                ('play_runtime', models.FloatField()),
                ('play_date', models.DateField()),
            ],
            options={
                'db_table': 'mcusermovie',
                'managed': False,
            },
        ),
    ]
